name: Сообщение об ошибке
description: Сообщить об ошибке или проблеме в работе бота
title: "[БАГ]: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Резюме
      description: Краткое описание проблемы
      placeholder: Опишите проблему...
    validations:
      required: true
  
  - type: textarea
    id: reproduction
    attributes:
      label: Шаги воспроизведения
      description: Как воспроизвести проблему?
      placeholder: |
        1. Перейти к '...'
        2. Нажать на '...'
        3. Увидеть ошибку
    validations:
      required: false
  
  - type: textarea
    id: expected
    attributes:
      label: Ожидаемое поведение
      description: Что должно было произойти?
      placeholder: Опишите ожидаемое поведение...
    validations:
      required: false
  
  - type: textarea
    id: actual
    attributes:
      label: Фактическое поведение
      description: Что произошло на самом деле?
      placeholder: Опишите фактическое поведение...
    validations:
      required: false
  
  - type: textarea
    id: environment
    attributes:
      label: Среда
      description: Версия приложения, commit, платформа/браузер/OS
      placeholder: |
        Версия: v1.0.0
        Commit: abc123def
        Платформа: Linux/Docker/Railway
    validations:
      required: false
  
  - type: textarea
    id: attachments
    attributes:
      label: Вложения
      description: Скриншоты, логи или другие файлы
      placeholder: Вставьте скриншоты или логи...
    validations:
      required: false
  
  - type: checkboxes
    id: checklist
    attributes:
      label: Чек-лист
      options:
        - label: Нет секретов (токены, API ключи и т.д.)
          required: true
        - label: Поискал похожие issues
          required: true
